name = "persistent-cart-worker"
main = "./dist/worker.js"
account_id = "e56b18ce4c0cf671554cd09cd9b5e6f2"
workers_dev = true
compatibility_date="2022-06-09"
local_protocol="http"
upstream_protocol="https"

kv_namespaces = [
  { binding = "CART_STORE", id = "8fc70b3374744319bd31db4b0a345d4b", preview_id = "8fc70b3374744319bd31db4b0a345d4b" }
]

[build]
command = "npm install && npm run build"

[miniflare]
upstream = "https:/staging-579.rainbowshops.com"
kv_persist = true
